修改了frame/panel/mainpanelcontrol.cpp文件，放开对第三方插件的宽度和高度的限制，不对第三方插件设置边距
linuxdeepin/dde-dock pull request #322
Opened 2020-11-04 09:55 UTC by q77190858

根据我的测试，1060行的
`if (pItem && pItem != trashPlugin && pItem != shutdownPlugin && pItem != keyboardPlugin && pItem !=notificationPlugin) {`
根本无法判断是不是垃圾桶、关机、键盘和通知插件，最后还是所有插件在循环里面执行了一遍，按道理是不用执行的，可是这个设置size还误打误撞是必要的，如果不设置垃圾桶、关机、键盘和通知插件的大小为固定值，这些插件就会消失，似乎1060行之前设置的size都没有效果，只有在这个判断中设置的才有效果

2020-11-05 00:58 UTC, juteman commented
Hello, here is a [Commit Specification](https://github.com/linuxdeepin/developer-center/wiki/Commit%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83). Following that or it will not be merged

2020-11-05 06:38 UTC, q77190858 commented
> Hello, here is a [Commit Specification](https://github.com/linuxdeepin/developer-center/wiki/Commit%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83). Following that or it will not be merged

thanks, i have modified my pr, I hope it will be merged!

2020-11-05 09:03 UTC, xmuli commented
> > Hello, here is a [Commit Specification](https://github.com/linuxdeepin/developer-center/wiki/Commit%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83). Following that or it will not be merged
> 
> thanks, i have modified my pr, I hope it will be merged!

ok

2020-11-06 07:17 UTC, xmuli requested changes
看了一下, git 提交混乱了, 直接在 github 网页上修改再提交, 实际是没有修改成功的.  建议关掉重新提交,  已经提交冲突了,无法合并 (猜测你是网页修改提交一次, 本地修改提交一次, 但是没有保持 rebase 一致?); 或者使用 git 解决分支冲突也行

![image](https://user-images.githubusercontent.com/33887845/98337007-e5302480-2042-11eb-92cd-e60b9b937a99.png)


![image](https://user-images.githubusercontent.com/33887845/98337134-1a3c7700-2043-11eb-887a-0e562018e95d.png)

2020-11-06 15:31 UTC, closed without merging

2020-11-10 01:23 UTC, xmuli commented
已经修复 [9188fff1](https://github.com/linuxdeepin/dde-dock/commit/9188fff15bdac20edbd14290bb1e44c1bcef28b5), 感谢你的反馈