fix: 修复程序同时支持XEmbed和SNI时，托盘出现双图标问题
linuxdeepin/dde-dock pull request #405
Opened 2021-11-26 06:39 UTC by tsic404

修复程序同时支持XEmbed和SNI时，托盘出现双图标问题

2021-11-26 09:38 UTC, zccrs requested changes

2021-11-26 09:38 UTC, zccrs commented on plugins/tray/trayplugin.cpp
> +    QDBusConnection conn = QDBusConnection::connectToBus(QDBusConnection::SessionBus, "org.freedesktop.DBus");
direct use the QDBusConnection::sessionBus()

2021-11-26 09:38 UTC, zccrs commented on plugins/tray/xembedtraywidget.cpp
> +    return pid;
Should close the X display if the "IS_WAYLAND_DISPLAY" is true

2021-11-26 09:38 UTC, zccrs commented on plugins/tray/trayplugin.cpp
> +    for (auto winid : xembedOnlyWinIdList) {
Can be processed together in the previous for-loop code block

2021-11-26 09:38 UTC, zccrs commented on plugins/tray/trayplugin.cpp
>          traySNIAdded(sinTrayKeyList.at(i), itemServicePaths.at(i));
Check the PID also for the SNI item

2021-11-29 03:43 UTC, zccrs requested changes

2021-11-29 03:43 UTC, zccrs commented on plugins/tray/abstracttraywidget.h
> +    uint m_ownerPID;
Move the member to the private scope

2021-11-29 03:43 UTC, zccrs commented on plugins/tray/trayplugin.cpp
> +    QDBusConnection conn = QDBusConnection::sessionBus();
The "conn" is first used at the 350 line, should define it at the first use nearby.

2021-11-29 03:43 UTC, zccrs commented on plugins/tray/trayplugin.cpp
> +    QList<quint32> newlyAdded;
newlyAddedWindowID

2021-11-29 03:43 UTC, zccrs commented on plugins/tray/trayplugin.cpp
> +        uint pid = conn.interface()->servicePid(dbusName);
Like the XEmbedTrayWidget::getWindowPID, should get the pid of the dbus item at there by the SNITrayWidget::xxxx.

2021-12-14 02:53 UTC, YihaoPeng commented
支持。正在被该问题困扰。

![image](https://user-images.githubusercontent.com/26923506/145924483-b9aac0da-2629-4d42-b4ee-55bee933991c.png)

2021-12-16 08:27 UTC, tsic404 commented
Internally merged and released version 5.4.69-1

2021-12-16 08:28 UTC, closed without merging

2022-02-28 11:17 UTC, YihaoPeng commented
It looks like the update hasn't reached UOS home edition yet.

![image](https://user-images.githubusercontent.com/26923506/155973505-b5a3f0f7-79cf-4583-bb39-5b187fb496aa.png)

Regardless of the technical details, as a user, I just want a well-rendered tray area instead of having 4 duplicated icons.

2022-03-01 05:06 UTC, zccrs commented
> 看起来这个更新还没有到达UOS家庭版。
> 
> ![image](https://user-images.githubusercontent.com/26923506/155973505-b5a3f0f7-79cf-4583-bb39-5b187fb496aa.png)
> 
> 作为用户，我只想有一个正常显示的托盘区域，而不是像这样出现4个相同的图标。

家庭版的更新周期和策略跟deepin不一致，你可以把问题报告到家庭版，这样才有希望尽快推送更新解决。