fix: calendar icon display error
linuxdeepin/dde-dock pull request #414
Opened 2022-03-02 06:17 UTC by kt286

https://bbs.deepin.org/post/232403

![image](https://user-images.githubusercontent.com/10684972/156306254-469ad178-011e-418e-9642-2a8f065917b0.png)

2022-04-29 23:38 UTC, kt286 commented
@BLumia 我这个改法其实不是很优雅，其他月份的图标都是用的 <path> 只有3月用的 <text> 建议你们找美工弄一下，看着统一

2022-04-30 05:38 UTC, BLumia commented
> 建议你们找美工弄一下，看着统一

同意这种说法，不过找美工那边应该是走另一个流程。设计那边改这个之前，我觉得也可以先以这种形式改 :)

2022-05-05 06:34 UTC, ssk-wh approved these changes

2022-05-05 06:38 UTC, ssk-wh requested changes
提交信息更新一下，按照上面的评论中的格式

2022-05-05 06:42 UTC, kt286 commented
> 提交信息更新一下，按照上面的评论中的格式

意思是不需要 Log 那行吗？还是描述要改成中文

2022-05-05 06:56 UTC, BLumia commented
> 提交信息更新一下，按照上面的评论中的格式

提交信息已经通过 commitlint 检查的情况就不用再更新了吧？

2022-05-05 07:19 UTC, ssk-wh commented
> > 提交信息更新一下，按照上面的评论中的格式
> 
> 提交信息已经通过 commitlint 检查的情况就不用再更新了吧？

哦，那就没问题了，我没注意到最新的提交

2022-05-05 07:19 UTC, ssk-wh approved these changes

2022-05-05 07:20 UTC, ssk-wh commented
OK

2022-05-05 07:38 UTC, BLumia commented
@kt286 试着回复一下 `\merge` 应该就可以合并了 :)

2022-05-05 07:44 UTC, kt286 commented
/merge

2022-05-05 07:45 UTC, merged