fix: the 3rd plugins can't show context menu
linuxdeepin/dde-dock pull request #450
Opened 2022-06-10 01:41 UTC by kt286

fix the 3rd plugins can't show context memu

Log: fix the 3rd plugins can't show context menu

2022-06-15 02:06 UTC, zccrs commented on frame/item/pluginsitem.cpp
> +            return (m_gsettings && m_gsettings->keys().contains("menuEnable") && m_gsettings->get("menuEnable").toBool()) ? void() : showContextMenu();
这个条件是不是写反了？

2022-06-15 02:29 UTC, kt286 commented on frame/item/pluginsitem.cpp
> +            return (m_gsettings && m_gsettings->keys().contains("menuEnable") && m_gsettings->get("menuEnable").toBool()) ? void() : showContextMenu();
没有
按照原来的逻辑 三方插件没有注册 gsettings ，就没法显示右键菜单，所以改成了 只有注册了 gsettings 并且 menuEnable 是 false 才调用 void() ，否则调用 showContextMenu()

2022-06-15 02:33 UTC, zccrs commented on frame/item/pluginsitem.cpp
> +            return (m_gsettings && m_gsettings->keys().contains("menuEnable") && m_gsettings->get("menuEnable").toBool()) ? void() : showContextMenu();
但是现在写的是只有注册了 gsettings ，并且 menuEnable 是true会调用 void()， 也就是不显示菜单。

2022-06-15 02:35 UTC, kt286 commented on frame/item/pluginsitem.cpp
> +            return (m_gsettings && m_gsettings->keys().contains("menuEnable") && m_gsettings->get("menuEnable").toBool()) ? void() : showContextMenu();
忘了加  ! 了......

2022-06-15 02:40 UTC, kt286 commented
/merge

2022-06-15 02:41 UTC, zccrs commented
> /merge

要构建完成后才能 merge

2022-06-15 02:42 UTC, kt286 commented
> 要构建完成后才能 merge

要是构建失败了可以 merge 吗？

2022-06-15 02:43 UTC, zccrs commented
> > 要构建完成后才能 merge
> 
> 要是构建失败了可以 merge 吗？

不可以呀

2022-06-15 02:47 UTC, zccrs requested changes
此提交需要将两个commit合并为一个，故暂且取消加分，由管理员手动合入

2022-06-15 02:53 UTC, kt286 commented
> 此提交需要将两个commit合并为一个，故暂且取消加分，由管理员手动合入

我改一下 force push

2022-06-15 02:53 UTC, zccrs commented
> > 此提交需要将两个commit合并为一个，故暂且取消加分，由管理员手动合入
> 
> 我改一下 force push

不用，我们手动合并，不然还得重新构建

2022-06-17 06:01 UTC, zccrs commented
代码已构建成功，deb包获取失败，忽略此类错误，本PR强制合入。

2022-06-17 06:05 UTC, merged