fix: the tray icon can't holded
linuxdeepin/dde-dock pull request #457
Opened 2022-07-13 06:52 UTC by kt286

the tray icon can't holded

Log: the tray icon can't holded

2022-07-18 03:46 UTC, donghualin submitted a review, later dismissed

2022-07-19 12:12 UTC, kt286 commented
I have read the CLA Document and I hereby sign the CLA

2022-08-11 02:08 UTC, ut003640 approved these changes

2022-08-11 02:35 UTC, kt286 commented
/merge

2022-08-11 11:48 UTC, ssk-wh commented
没有看明白为什么要修改，这里以前是为了异步处理，同步的话有一个小概率导致dbus调用无限卡死的问题

2022-08-12 05:26 UTC, kt286 commented
> 没有看明白为什么要修改，这里以前是为了异步处理，同步的话有一个小概率导致dbus调用无限卡死的问题

现在托盘图标不能固定到箭头右边了 重启后会又跑到左边

2022-09-14 07:14 UTC, ssk-wh commented
> > 没有看明白为什么要修改，这里以前是为了异步处理，同步的话有一个小概率导致dbus调用无限卡死的问题
> 
> 现在托盘图标不能固定到箭头右边了 重启后会又跑到左边

和这笔提交中的修改没什么关联，只是改了DBus通信的同步异步机制，不会影响我们驻留图标的情况，而且修改后会出现一个历史问题：部分托盘服务的DBus调用后会卡死，导致任务栏方面也会卡死，所以才使用的异步

2022-09-14 07:15 UTC, ssk-wh requested changes
和要解决的问题看不出关联

2022-09-15 11:07 UTC, kt286 commented
> 和要解决的问题看不出关联

可问题是确实影响图标驻留了，修改完也确实可以 以我的技术只能改到这个程度 你们可以搞搞这个问题

2022-09-20 08:40 UTC, squallliu commented
> > > 没有看明白为什么要修改，这里以前是为了异步处理，同步的话有一个小概率导致dbus调用无限卡死的问题
> > 
> > 
> > 现在托盘图标不能固定到箭头右边了 重启后会又跑到左边
> 
> 和这笔提交中的修改没什么关联，只是改了DBus通信的同步异步机制，不会影响我们驻留图标的情况，而且修改后会出现一个历史问题：部分托盘服务的DBus调用后会卡死，导致任务栏方面也会卡死，所以才使用的异步

你们自己用固定图标吗？现在只有 better-dde 的 dock 能固定，官方的不能固定好久了

2022-10-21 02:02 UTC, ut003640 approved these changes

2022-10-21 02:13 UTC, ut003640 reviewed
initSNIPropertys();
这个函数改成异步的方式加载

2022-10-23 11:16 UTC, kt286 commented
> initSNIPropertys(); 这个函数改成异步的方式加载

fix with https://github.com/linuxdeepin/dde-dock/commit/968140e6e2b3101942f2f706c215ae38336538fd

2022-10-23 11:16 UTC, closed without merging