feat: 添加配置 hover 显示桌面的时间
linuxdeepin/dde-dock pull request #706
Opened 2022-10-17 02:02 UTC by kegechen

不影响默认行为，默认该配置为 0 即立刻显示或恢复
如果需要可以进行 dconfig 配置

Log: 添加配置显示桌面的悬浮时间
Change-Id: I0b394bf02717b6ba1abe1e5c86fab82d314f39fc

2022-10-20 09:12 UTC, ssk-wh requested changes
没什么问题，稍作修改就可合入

2022-10-20 09:12 UTC, ssk-wh commented on frame/window/components/desktop_widget.cpp
> +        if (m_timer)
同下

2022-10-20 09:12 UTC, ssk-wh commented
@ut003640

2022-10-20 09:20 UTC, kegechen commented on frame/window/mainwindow.cpp
> +            const int ms = m_dconfig.data()->value("toggleDesktopInterval", 0).toInt();
这个是为了和原来使用习惯保持一致。

2022-10-20 09:21 UTC, kegechen commented on frame/window/components/desktop_widget.cpp
> +    if (m_timer) {
小心驶得万年船嘛

2022-10-20 09:24 UTC, ssk-wh reviewed
OK

2022-10-20 09:25 UTC, ssk-wh approved these changes

2022-10-21 02:52 UTC, ut003640 approved these changes

2022-10-27 05:10 UTC, merged