fix: make keyboard layout plugin size fixed
linuxdeepin/dde-dock pull request #790
Opened 2023-03-07 06:46 UTC by tsic404

tray size shou be fixed, should not change follow systemd font size.
add text change info from sourceIndicatorWidget to display indicatorWidget
fix https://github.com/linuxdeepin/developer-center/issues/3834

log:

2023-03-15 05:18 UTC, tsic404 commented
/check build

2023-04-14 09:47 UTC, BLumia commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    qf.setPixelSize(11);
这个尺寸是设计给定的，且确定不需要从 fontmanager 获取的吗？

2023-04-14 09:53 UTC, tsic404 commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    qf.setPixelSize(11);
调整到16，与icon大小一致，但是遇到不居中问题，看了下20 也是不居中 :(

2023-04-14 10:07 UTC, tsic404 commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    qf.setPixelSize(11);
<img width="145" alt="image" src="https://user-images.githubusercontent.com/48748112/232015836-7c39927b-4da4-49cd-b663-c46669576c2e.png">

2023-04-24 02:03 UTC, asterwyx commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    m_label->setAlignment(Qt::AlignHCenter | Qt::AlignVCenter);
这个地方如果直接写AlignCenter，效果不一样吗

2023-05-22 07:37 UTC, tsic404 commented
通过layout->setContentsMargins的方式垫高全小写的文本，达到小写文本局中效果
<img width="191" alt="image" src="https://github.com/linuxdeepin/dde-dock/assets/48748112/5f71a8fc-ae27-4274-ab6f-09e7aeb5b86d">
(远程连接，所以有点糊 :(

2023-05-22 08:12 UTC, BLumia commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +#include <qnamespace.h>
这个不对吧

2023-05-22 08:16 UTC, tsic404 commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +#include <qnamespace.h>
clangd自动补全带进来的 :(

2023-05-23 01:42 UTC, BLumia submitted a review, later dismissed

2023-05-23 02:26 UTC, asterwyx requested changes

2023-05-23 02:26 UTC, asterwyx commented on frame/window/tray/tray_delegate.h
> +// 16 x 16 will make icon being cutted, reserve 2 pixel for each side to prevent be cutted
```suggestion
// 16 x 16 will make the icon be cut, reserve 2 pixels for each side to prevent being gutted
```
来自Grammarly

2023-05-23 02:26 UTC, asterwyx commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    m_layout->setContentsMargins(0, 0, 0, text.isLower()? 3 : 0);
这个地方对所有的小写字母都是生效的吗？

2023-05-23 02:26 UTC, asterwyx commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    m_label->setFont(qf);
为什么绑定之后又设置了pixelSize

2023-05-23 02:26 UTC, asterwyx commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    setLayout(m_layout);
在构造的时候已经传了this作为参数，m_layout会自动挂在this下作为布局，这里不应该再使用m_layout，会引起警告，但是可以看一下需不需要activate或者update layout。

2023-05-23 02:26 UTC, asterwyx commented on frame/window/tray/widgets/indicatortrayitem.cpp
> +    // 3 pixel adjust for lowercase character, which can make lowercase character keep in center
```suggestion
    // 3 pixels adjust for the lowercase characters, which can make lowercase character keep in the center
```
来自Grammarly。

2023-05-26 05:16 UTC, asterwyx approved these changes

2023-05-29 01:55 UTC, tsic404 commented
/merge

2023-05-29 01:55 UTC, merged