fix: Missing radius for tray's background
linuxdeepin/dde-dock pull request #798
Opened 2023-03-08 08:46 UTC by 18202781743

Add a common function to draw rounded background.

Issue: https://github.com/linuxdeepin/developer-center/issues/3744

2023-03-09 09:37 UTC, asterwyx requested changes

2023-03-09 09:37 UTC, asterwyx commented on frame/window/traymanagerwindow.cpp
> +    // draw highlight background for specital path.
```suggestion
    // draw highlight background for special path.
```

2023-03-09 09:37 UTC, asterwyx commented on frame/window/traymanagerwindow.cpp
> +
函数名和含义不对应，改成updateHighlightArea

2023-03-10 00:49 UTC, asterwyx submitted a review, later dismissed

2023-03-13 08:07 UTC, tsic404 approved these changes

2023-03-14 01:03 UTC, merged