chore: fix build warning
linuxdeepin/dde-dock pull request #810
Opened 2023-03-22 12:27 UTC by tsic404

fix package warning
1. replace deprecated QPalette::ColorRole Background and Foreground
2. replace deprecated Qt::SystemLocaleLongDate
3. replace deprecated QMouseEvent constructor
4. CMakeLists.txt rectification

log: remove build warnings

2023-03-23 03:06 UTC, BLumia requested changes

2023-03-23 03:06 UTC, BLumia commented on frame/util/abstractpluginscontroller.cpp
> +    // qDebug() << objectName() << "init plugin finished: " << interface->pluginName();
留着有别的用吗？没的话直接删掉？

2023-03-23 03:06 UTC, BLumia commented on plugins/bluetooth/CMakeLists.txt
> +  PkgConfig::QGSettings
向上一点 target_include_directories 的地方，`${QGSettings_INCLUDE_DIRS}` 就可以去掉了吧

2023-03-23 03:06 UTC, BLumia commented on plugins/datetime/CMakeLists.txt
> +  PkgConfig::QGSettings
同上，以及 DTK 的查找和使用应该也可以一并改

2023-03-23 03:06 UTC, BLumia commented on plugins/display/CMakeLists.txt
> +  PkgConfig::QGSettings
同上

2023-03-23 03:06 UTC, BLumia commented on plugins/media/CMakeLists.txt
> +  PkgConfig::QGSettings
同上

2023-03-23 05:30 UTC, tsic404 commented on plugins/datetime/CMakeLists.txt
> +  PkgConfig::QGSettings
DtkWidget 仓库里面的应该还不支持

2023-03-24 05:24 UTC, tsic404 commented
/check build

2023-03-26 03:29 UTC, BLumia approved these changes

2023-03-26 11:16 UTC, merged