feat: DockPopupWindow改用DBlurEffectWidget实现
linuxdeepin/dde-dock pull request #819
Opened 2023-04-07 07:05 UTC by ArchieMeng

DockPopupWindow改为使用DBlurEffectWidget来实现新的设计，以及摆脱原来DArrowRectangle出现的侧边任务栏PopupWindow圆角显示不对称的问题．同时，当前遗留有QuickPlugin与DateTimePlayer的HoverTip Padding和其他不太一致的问题．

Log: DockPopupWindow改用DBlurEffectWidget实现

2023-04-10 06:18 UTC, tsic404 requested changes

2023-04-10 06:19 UTC, tsic404 commented
而且高效模式下，时间显示区域消失了🫠

2023-04-10 07:03 UTC, ArchieMeng commented
> 而且高效模式下，时间显示区域消失了🫠

已更新，就是因为那里没有分位置设置SizePolicy导致的．

2023-04-10 08:32 UTC, tsic404 requested changes
插件区域点击，坐标计算忘记修改

2023-04-10 08:42 UTC, tsic404 requested changes

2023-04-10 08:42 UTC, tsic404 commented on plugins/sound/soundapplet.cpp
> +
多余的空格？

2023-04-10 08:42 UTC, tsic404 commented on plugins/sound/soundapplet.cpp
> +
多余的空格？

2023-04-11 08:39 UTC, tsic404 approved these changes

2023-04-11 08:39 UTC, tsic404 commented
/merge

2023-04-11 08:40 UTC, merged