feat: add plugin notification
linuxdeepin/dde-dock pull request #946
Opened 2024-01-04 06:25 UTC by asterwyx

Add plugin notification to show notification center. Notification is a
fixed plugin.

Log: add plugin notification

2024-01-05 02:48 UTC, asterwyx commented
/integrate

2024-01-05 03:15 UTC, tsic404 commented on plugins/notification/notificationplugin.cpp
> +    return tr("Notification");
翻译文件更新？

2024-01-05 05:37 UTC, asterwyx commented on plugins/notification/notificationplugin.cpp
> +    return tr("Notification");
Done

2024-01-05 05:38 UTC, asterwyx commented
/integrate

2024-01-05 06:08 UTC, tsic404 approved these changes

2024-01-05 06:11 UTC, tsic404 commented
<img width="821" alt="image" src="https://github.com/linuxdeepin/dde-dock/assets/48748112/8f60f22e-bca6-471a-bcee-e918b92a49f2">
是不是没有做？

2024-01-05 06:11 UTC, tsic404 requested changes
<img width="821" alt="image" src="https://github.com/linuxdeepin/dde-dock/assets/48748112/2916b430-763f-473c-a083-20c351b2c3c0">

2024-01-05 07:13 UTC, Zeno-sole commented
/integrate

2024-01-08 05:33 UTC, tsic404 approved these changes

2024-01-08 05:34 UTC, asterwyx commented
/integrate

2024-01-08 05:41 UTC, merged

2024-01-08 05:41 UTC, asterwyx commented
/integrate